redis:
  image: redis:alpine
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/usr/src/app
    - ./node_modules:/usr/src/app/node_modules
  restart: always
  links:
    - redis
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000
